apiVersion: v1
kind: Namespace
metadata:
  name: eclipse-che-images
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: system:image-puller
  namespace: eclipse-che-images
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: podman-basic
  namespace: eclipse-che-images
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: podman-kubedock
  namespace: eclipse-che-images
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: quarkus
  namespace: eclipse-che-images
